name: Test Terraform Destroy
on:
  workflow_dispatch: {}
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        terraform_version:
          - '0.12.0'
          - '0.12.31'
          - '0.13.0'
          - '0.14.0'
          - '0.15.0'
          - '1.0.0'
          - '1.1.0'
          - '1.2.0'
          - '1.3.0'
          - '1.3.4'
          - '1.3.5'
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform_version }}
      - run: terraform init
      - name: terraform apply
        run: terraform apply -auto-approve
      - name: terraform state rm
        run: terraform state rm null_resource.test
      - run: terraform refresh
      - name: terraform destroy
        run: terraform destroy -auto-approve
